name: Update Weather Forecast

on:
  schedule:
    # This cron expression runs every hour on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install node-fetch@2
      
      - name: Fetch and update weather data
        run: node update-weather.js
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          LOCATION: "Your_City,Your_Country" # Replace with your location
      
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add forecast.json
          git commit -m "Update weather forecast [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
